/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Bending10V2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-148.57, 2.37, -85.7]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      >
        <mesh
          geometry={nodes.Bending006.geometry}
          material={materials["Moving.010"]}
        />
        <mesh
          geometry={nodes.Bending006_1.geometry}
          material={materials["Pipe.022"]}
        />
        <mesh
          geometry={nodes.Bending006_2.geometry}
          material={materials["White.010"]}
        />
        <mesh
          geometry={nodes.Bending006_3.geometry}
          material={materials["Material.049"]}
        />
        <mesh
          geometry={nodes.Bending006_4.geometry}
          material={materials["Black.026"]}
        />
        <mesh
          geometry={nodes.Bending006_5.geometry}
          material={materials.Rail}
        />
        <mesh
          geometry={nodes.Bending006_6.geometry}
          material={materials.aluminium}
        />
        <mesh
          geometry={nodes.Bending006_7.geometry}
          material={materials["black.010"]}
        />
        <mesh
          geometry={nodes.Bending006_8.geometry}
          material={materials.grey_base}
        />
        <mesh
          geometry={nodes.Bending006_9.geometry}
          material={materials.grey}
        />
        <mesh
          geometry={nodes.Bending006_10.geometry}
          material={materials.copper}
        />
        <mesh
          geometry={nodes.Bending006_11.geometry}
          material={materials.ivory_gripper}
        />
        <mesh
          geometry={nodes.Bending006_12.geometry}
          material={materials.ivory}
        />
        <mesh
          geometry={nodes.Bending006_13.geometry}
          material={materials["ivory_arm.010"]}
        />
        <mesh
          geometry={nodes.Bending006_14.geometry}
          material={materials.grey_rotation}
        />
        <mesh
          geometry={nodes.Bending006_15.geometry}
          material={materials["Metal.011"]}
        />
        <mesh
          geometry={nodes.Bending006_16.geometry}
          material={materials["Black.027"]}
        />
        <mesh
          geometry={nodes.Bending006_17.geometry}
          material={materials["Pipe.023"]}
        />
        <mesh
          geometry={nodes.Bending006_18.geometry}
          material={materials["Blue.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Bending10V2.glb");
