/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/BrazingTable.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-168.27, 2.37, 65.66]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.003, 0.003, 0.003]}
      >
        <mesh
          geometry={nodes.Brazing001.geometry}
          material={materials["TableLeg.003"]}
        />
        <mesh
          geometry={nodes.Brazing001_1.geometry}
          material={materials["Metal.012"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/BrazingTable.glb");
