/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/BrazingAutoV2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-137.76, 3.7, 45.71]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.003, 0.003, 0.003]}
      >
        <mesh
          geometry={nodes.Brazing_Type3_Combo002.geometry}
          material={materials["Material.055"]}
        />
        <mesh
          geometry={nodes.Brazing_Type3_Combo002_1.geometry}
          material={materials.Button}
        />
        <mesh
          geometry={nodes.Brazing_Type3_Combo002_2.geometry}
          material={materials["Red.003"]}
        />
        <mesh
          geometry={nodes.Brazing_Type3_Combo002_3.geometry}
          material={materials.Box}
        />
        <mesh
          geometry={nodes.Brazing_Type3_Combo002_4.geometry}
          material={materials.Monitor}
        />
        <mesh
          geometry={nodes.Brazing_Type3_Combo002_5.geometry}
          material={materials["Green.003"]}
        />
        <mesh
          geometry={nodes.Brazing_Type3_Combo002_6.geometry}
          material={materials.Yellow}
        />
        <mesh
          geometry={nodes.Brazing_Type3_Combo002_7.geometry}
          material={materials["Pipe.012"]}
        />
        <mesh
          geometry={nodes.Brazing_Type3_Combo002_8.geometry}
          material={materials["Moving.007"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/BrazingAutoV2.glb");
