/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/CuttingV2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-38.9, 5.21, -69.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0024}
      >
        <mesh
          geometry={nodes.Cutting_short_1.geometry}
          material={materials["Material.071"]}
        />
        <mesh
          geometry={nodes.Cutting_short_2.geometry}
          material={materials["Material.072"]}
        />
        <mesh
          geometry={nodes.Cutting_short_3.geometry}
          material={materials["Material.073"]}
        />
        <mesh
          geometry={nodes.Cutting_short_4.geometry}
          material={materials["Material.074"]}
        />
        <mesh
          geometry={nodes.Cutting_short_5.geometry}
          material={materials["Material.075"]}
        />
        <mesh
          geometry={nodes.Cutting_short_6.geometry}
          material={materials.Moter}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/CuttingV2.glb");
