/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Forming10V2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-177.94, 3.61, -88.46]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.02, 0.02, -0.02]}
      >
        <mesh geometry={nodes.Bending003.geometry} material={materials.White} />
        <mesh
          geometry={nodes.Bending003_1.geometry}
          material={materials["Black.021"]}
        />
        <mesh
          geometry={nodes.Bending003_2.geometry}
          material={materials.Black2}
        />
        <mesh
          geometry={nodes.Bending003_3.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Bending003_4.geometry}
          material={materials.Moving}
        />
        <mesh
          geometry={nodes.Bending003_5.geometry}
          material={materials.Green}
        />
        <mesh geometry={nodes.Bending003_6.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Bending003_7.geometry}
          material={materials.Base}
        />
        <mesh
          geometry={nodes.Bending003_8.geometry}
          material={materials["Material.047"]}
        />
        <mesh
          geometry={nodes.Bending003_9.geometry}
          material={materials.Door}
        />
        <mesh
          geometry={nodes.Bending003_10.geometry}
          material={materials.Blue}
        />
        <mesh
          geometry={nodes.Bending003_11.geometry}
          material={materials["Metal.004"]}
        />
        <mesh
          geometry={nodes.Bending003_12.geometry}
          material={materials.Pipe}
        />
        <mesh
          geometry={nodes.Bending003_13.geometry}
          material={materials["Blue.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Forming10V2.glb");
