/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Lamp/LampLeg0304.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.LampLeg004.geometry}
        material={materials["Black.018"]}
        position={[-170.18, 4.1, 26.58]}
        scale={[1.33, 2.12, 1.33]}
      />
    </group>
  );
}

useGLTF.preload("/Model/Lamp/LampLeg0304.glb");
