/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Lamp/LampLeg11.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.LampLeg11.geometry}
        material={materials["Black.018"]}
        position={[34.7, 5.1, -53.5]}
        scale={[1.32, 2.12, 1.33]}
      />
    </group>
  );
}

useGLTF.preload("/Model/Lamp/LampLeg11.glb");
