/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Lamp/Lamp.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.LampPro.geometry}
        material={nodes.LampPro.material}
        scale={[0.23, 0.29, 0.23]}
      >
        <meshLambertMaterial color={props.color} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Model/Lamp/Lamp.glb");
