/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Lamp/LampLeg10.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.LampLeg10.geometry}
        material={nodes.LampLeg10.material}
        position={[-148.26, 4.12, -87.16]}
        scale={[1.33, 2.12, 1.33]}
      />
      <mesh
        geometry={nodes.LampLeg10Form.geometry}
        material={nodes.LampLeg10Form.material}
        position={[-177.3, 4.27, -83.51]}
        scale={[1.6, 2.12, 1.33]}
      />
    </group>
  );
}

useGLTF.preload("/Model/Lamp/LampLeg10.glb");
