/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Lamp/LampLeg09.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.LampLeg09.geometry}
        material={materials["Black.018"]}
        position={[-192, 4.58, -34.56]}
        scale={[1.33, 2.12, 1.33]}
      />
    </group>
  );
}

useGLTF.preload("/Model/Lamp/LampLeg09.glb");
