/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Lamp/LampLeg01.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.LampLegTable.geometry}
        material={nodes.LampLegTable.material}
        position={[-168.27, 3.45, 65.66]}
        scale={[1.33, 2.12, 1.33]}
      />
      <mesh
        geometry={nodes.LampLegSemi.geometry}
        material={nodes.LampLegSemi.material}
        position={[-99.14, 4.17, 49.85]}
        scale={[1.33, 2.12, 1.33]}
      />
    </group>
  );
}

useGLTF.preload("/Model/Lamp/LampLeg01.glb");
