/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Lamp/LampLeg07Yellow.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.LampLeg07Yellow.geometry}
        material={materials["Black.018"]}
        position={[-93.37, 4.53, -23.69]}
        scale={[1.28, 2.12, 1.33]}
      />
    </group>
  );
}

useGLTF.preload("/Model/Lamp/LampLeg07Yellow.glb");
