/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/CopperStore.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.CopperStore.geometry}
        material={materials["BodyGreen.002"]}
        position={[127.45, 1.47, -5.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0}
      />
    </group>
  );
}

useGLTF.preload("/Model/Compo/CopperStore.glb");
