/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/FloorV2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={-88.19}>
        <mesh geometry={nodes.Plane003.geometry} material={materials.Floor} />
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials.Circle093__0}
        />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials.Gas} />
        <mesh geometry={nodes.Plane003_3.geometry} material={materials.GasP} />
        <mesh geometry={nodes.Plane003_4.geometry} material={materials.GasY} />
        <mesh geometry={nodes.Plane003_5.geometry} material={materials.GasB} />
        <mesh geometry={nodes.Plane003_6.geometry} material={materials.GasR} />
        <mesh geometry={nodes.Plane003_7.geometry} material={materials.GasG} />
        <mesh
          geometry={nodes.Plane003_8.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Compo/FloorV2.glb");
