/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/GasBrazingV2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-121.76, 6.5, 63.25]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.0027, 0.00105, 0.002]}
      >
        <mesh
          geometry={nodes.Line_GAS_Brazing001.geometry}
          material={materials["Gas.001"]}
        />
        <mesh
          geometry={nodes.Line_GAS_Brazing001_1.geometry}
          material={materials["GasP.001"]}
        />
        <mesh
          geometry={nodes.Line_GAS_Brazing001_2.geometry}
          material={materials["GasY.001"]}
        />
        <mesh
          geometry={nodes.Line_GAS_Brazing001_3.geometry}
          material={materials["GasB.001"]}
        />
        <mesh
          geometry={nodes.Line_GAS_Brazing001_4.geometry}
          material={materials["GasR.001"]}
        />
        <mesh
          geometry={nodes.Line_GAS_Brazing001_5.geometry}
          material={materials["GasG.001"]}
        />
        <mesh
          geometry={nodes.Line_GAS_Brazing001_6.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Compo/GasBrazingV2.glb");
