/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/InnerStore.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[143.98, 4.32, -62.79]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ชั้นวาง_Inner-1"].geometry}
          material={materials["BodyGreen.014"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ชั้นวาง_Inner-1_1"].geometry}
          material={materials["Material.050"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ชั้นวาง_Inner-1_2"].geometry}
          material={materials.Plastic}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Compo/InnerStore.glb");
