/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/OuterStore.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[2.09, 2.88, -22.4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-5.21, 5.21, -2.16]}
      >
        <mesh
          geometry={nodes.Palette_pallet_0001.geometry}
          material={materials["pallet.001"]}
        />
        <mesh
          geometry={nodes.Palette_pallet_0001_1.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.Palette_pallet_0001_2.geometry}
          material={materials["Material.022"]}
        />
      </group>
      <group position={[23.63, 2.28, -28.3]} scale={[0.09, 1.35, 0.09]}>
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.021"]}
        />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.black} />
        <mesh
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          geometry={nodes.Cylinder_3.geometry}
          material={materials["Black.014"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Compo/OuterStore.glb");
