/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/PalletJack.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-5.71, 1.18, 40.83]} scale={0.99}>
        <mesh
          geometry={nodes.pCube3_Main_Body_Texture_0.geometry}
          material={materials.Main_Body_Texture}
        />
        <mesh
          geometry={nodes.pCube3_Main_Body_Texture_0_1.geometry}
          material={materials.aiStandardSurface4}
        />
        <mesh
          geometry={nodes.pCube3_Main_Body_Texture_0_2.geometry}
          material={materials.Chrome_Pistons_Mat}
        />
        <mesh
          geometry={nodes.pCube3_Main_Body_Texture_0_3.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.pCube3_Main_Body_Texture_0_4.geometry}
          material={materials.Main_Wheel_Mat}
        />
        <mesh
          geometry={nodes.pCube3_Main_Body_Texture_0_5.geometry}
          material={materials.Aluminum_Bolts_Mat}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Compo/PalletJack.glb");
