/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/StoreBox.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[14.43, 1.53, 2.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[6.17, 6.17, 2.56]}
      >
        <mesh
          geometry={nodes.Palette_pallet_0.geometry}
          material={materials.pallet}
        />
        <mesh
          geometry={nodes.Palette_pallet_0_1.geometry}
          material={materials["lambert1.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Compo/StoreBox.glb");
