/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/StoreCopper.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-37.82, 1.81, -26.9]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-6.17, 6.17, -2.56]}
      >
        <mesh
          geometry={nodes.Palette_pallet_0002.geometry}
          material={materials.Copper}
        />
        <mesh
          geometry={nodes.Palette_pallet_0002_1.geometry}
          material={materials["Material.069"]}
        />
        <mesh
          geometry={nodes.Palette_pallet_0002_2.geometry}
          material={materials["pallet.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Compo/StoreCopper.glb");
