/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/Wall.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      {/* Wall-top */}
      <group position={[-3.23, 7.59, -100.25]} scale={[-8.37, -8.37, 8.37]}>
        <mesh
          geometry={nodes.Cube018.geometry}
          material={nodes.Cube018.material}
        />
        <mesh
          geometry={nodes.Cube018_1.geometry}
          material={nodes.Cube018_1.material}
        />
      </group>

      {/* Wall-bottom */}
      <group position={[-3.23, 7.59, 89.53]} scale={-8.37}>
        <mesh
          geometry={nodes.Cube018.geometry}
          material={nodes.Cube018.material}
        />
        <mesh
          geometry={nodes.Cube018_1.geometry}
          material={nodes.Cube018_1.material}
        />
      </group>

      {/* Wall-left */}
      <mesh
        geometry={nodes.WallShort1.geometry}
        material={nodes.WallShort1.material}
        position={[-189.26, 7.1, -3.03]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-11.92, -8.37, 8.37]}
      />

      {/* Wall-right */}
      <mesh
        geometry={nodes.WallShort1001.geometry}
        material={nodes.WallShort1001.material}
        position={[177.11, 7.1, -3.03]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[11.92, -8.37, 8.37]}
      />
    </group>
  );
}

useGLTF.preload("/Model/Compo/Wall.glb");
