/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Compo/WarehouseV2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[122.87, 8.9, 76.52]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.68, 1.68, 2.69]}
      >
        <mesh
          geometry={nodes.Cube017.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Cube017_1.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          geometry={nodes.Cube017_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube017_3.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          geometry={nodes.Cube017_4.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          geometry={nodes.Cube017_5.geometry}
          material={materials["Material.046"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Compo/WarehouseV2.glb");
