/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/CuttingCopper.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[153.15, 1.9, -9.76]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010"].geometry}
          material={materials["BodyBlue.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010_1"].geometry}
          material={materials["Metal.004"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010_2"].geometry}
          material={materials["Button.001"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010_3"].geometry}
          material={materials["ButtonEmer.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010_4"].geometry}
          material={materials["Black.004"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010_5"].geometry}
          material={materials["Copper.004"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010_6"].geometry}
          material={materials["BodyGreen.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010_7"].geometry}
          material={materials["Monitor.002"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_Cutting1-4010_8"].geometry}
          material={materials["BodyBlue.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/CuttingCopper.glb");
