/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/ExtruderInner.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[154.01, 3.23, -88.44]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1"].geometry}
          material={materials["Material.051"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_1"].geometry}
          material={materials["Monitor.007"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_2"].geometry}
          material={materials["ButtonEmer.009"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_3"].geometry}
          material={materials["LampGreen.002"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_4"].geometry}
          material={materials["LampRed.001"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_5"].geometry}
          material={materials["Metal.013"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_6"].geometry}
          material={materials["ControlBox.008"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_7"].geometry}
          material={materials["Button.008"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_8"].geometry}
          material={materials["BodyGreen.015"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_ตู้_Contor_GAS-1_9"].geometry}
          material={materials["Black.015"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/ExtruderInner.glb");
