/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/HRolling.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[130.94, 2.35, 11.24]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002"].geometry}
          material={materials["BodyGreen.001"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_1"].geometry}
          material={materials["Metal.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_2"].geometry}
          material={materials["Black.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_3"].geometry}
          material={materials["ButtonEmer.002"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_4"].geometry}
          material={materials["ControlBox.002"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_5"].geometry}
          material={materials["BodyGreen.005"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_6"].geometry}
          material={materials["Metal.007"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_7"].geometry}
          material={materials["Black.005"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_8"].geometry}
          material={materials["BodyBlue.006"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_9"].geometry}
          material={materials["Button.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_10"].geometry}
          material={materials["ButtonEmer.005"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1002_11"].geometry}
          material={materials["ControlBox.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/HRolling.glb");
