/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/InsertManual.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[72.78, 2.15, -4.16]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0}
      >
        <mesh
          geometry={nodes.CopperInsert.geometry}
          material={materials["BodyBlue.005"]}
        />
        <mesh
          geometry={nodes.CopperInsert_1.geometry}
          material={materials["Metal.006"]}
        />
        <mesh
          geometry={nodes.CopperInsert_2.geometry}
          material={materials["BodyGreen.004"]}
        />
        <mesh
          geometry={nodes.CopperInsert_3.geometry}
          material={materials["Button.002"]}
        />
        <mesh
          geometry={nodes.CopperInsert_4.geometry}
          material={materials["ButtonEmer.004"]}
        />
        <mesh
          geometry={nodes.CopperInsert_5.geometry}
          material={materials["ControlBox.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/InsertManual.glb");
