/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/InsertSemiAuto4M.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[130.94, 2.35, 11.24]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001"].geometry}
          material={materials["BodyGreen.001"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001_1"].geometry}
          material={materials["Metal.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001_2"].geometry}
          material={materials["Black.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001_3"].geometry}
          material={materials["BodyBlue.002"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001_4"].geometry}
          material={materials["ButtonEmer.002"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001_5"].geometry}
          material={materials["Monitor.001"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001_6"].geometry}
          material={materials["White.001"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001_7"].geometry}
          material={materials["Copper.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เสา_itoskay-1001_8"].geometry}
          material={materials["ControlBox.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/InsertSemiAuto4M.glb");
