/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/InsulationRolling.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[58.86, 2.68, -26.36]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1"].geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_1"].geometry}
          material={materials["Button.004"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_2"].geometry}
          material={materials["Monitor.003"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_3"].geometry}
          material={materials["BodyBlue.007"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_4"].geometry}
          material={materials["Black.007"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_5"].geometry}
          material={materials["ControlBox.005"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_6"].geometry}
          material={materials["BodyGreen.006"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_7"].geometry}
          material={materials["Black.006"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_8"].geometry}
          material={materials["ButtonEmer.006"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่องม้วน_insu-1_9"].geometry}
          material={materials["BodyGreen.007"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/InsulationRolling.glb");
