/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/InsulationHeat.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[103.74, 2.28, -26]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002"].geometry}
          material={materials["Metal.008"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_1"].geometry}
          material={materials["BodyGreen.011"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_2"].geometry}
          material={materials["Button.005"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_3"].geometry}
          material={materials["ButtonEmer.007"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_4"].geometry}
          material={materials["Monitor.004"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_5"].geometry}
          material={materials["Black.010"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_6"].geometry}
          material={materials.LampRed}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_7"].geometry}
          material={materials["ControlBox.006"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_8"].geometry}
          material={materials["Material.047"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_9"].geometry}
          material={materials.LampGreen}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_10"].geometry}
          material={materials["BodyGreen.008"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_11"].geometry}
          material={materials["BodyGreen.009"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_12"].geometry}
          material={materials["BodyGreen.010"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_13"].geometry}
          material={materials["BodyGreen.012"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_14"].geometry}
          material={materials["Monitor.005"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_15"].geometry}
          material={materials["Metal.011"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_16"].geometry}
          material={materials["Black.011"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_สายพานหน้า-1002_17"].geometry}
          material={materials["LampGreen.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/InsulationHeat.glb");
