/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/SlitterEmboss.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[157.52, 1.3, -23.34]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_slitter-1"].geometry}
          material={materials["BodyGreen.013"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_slitter-1_1"].geometry}
          material={materials["Button.006"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_slitter-1_2"].geometry}
          material={materials["Monitor.006"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_slitter-1_3"].geometry}
          material={materials["BodyBlue.008"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_slitter-1_4"].geometry}
          material={materials["Black.012"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_slitter-1_5"].geometry}
          material={materials["Material.049"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/SlitterEmboss.glb");
