/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Model/Pipekit/VRolling.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[115.86, 2.43, 25.67]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0}
      >
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่อง_Inser-8001"].geometry}
          material={materials["BodyBlue.001"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่อง_Inser-8001_1"].geometry}
          material={materials.Button}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่อง_Inser-8001_2"].geometry}
          material={materials["ButtonEmer.001"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่อง_Inser-8001_3"].geometry}
          material={materials["Black.002"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่อง_Inser-8001_4"].geometry}
          material={materials["Metal.002"]}
        />
        <mesh
          geometry={nodes["Line_Pipekit_3D_-_เครื่อง_Inser-8001_5"].geometry}
          material={materials["ControlBox.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Model/Pipekit/VRolling.glb");
